apiVersion: v1
kind: Service
metadata:
  name: demo-deploy
  namespace: d-demo1
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demo-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080